name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      inputs:
        region:
          description: 'AWS Region'
          required: true
          default: 'us-east-1'

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@master

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ${{ github.event.inputs.region}}

      - name: Configure environment name
        id: env-name
        env:
            REPO: ${{ github.repository }}
        run: |
            ENVIRONMENT=`echo $REPO | tr "/" "-"`
            echo "Environment name: $ENVIRONMENT"
            echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
  
      # Deploy to AWS CloudFormation
      - name: Deploy S3 bucket
        id: s3-bucket
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: ${{ steps.env-name.outputs.environment }}-cluster
          template: dummybucketpezoa.s3
          no-fail-on-empty-changeset: "1"
